"""Run once: python generate_candidates.py  →  writes data/candidates.json"""
import json
from pathlib import Path

Path("data").mkdir(exist_ok=True)

candidates = [
  # ── PERFECT MATCHES (10): Senior, full Python/Django|FastAPI/PostgreSQL/Docker/AWS/Redis ──
  {"id":"CAND001","name":"Sarah Chen","title":"Senior Backend Engineer","current_company":"Stripe","location":"Remote","skills":["Python","Django","FastAPI","PostgreSQL","Docker","AWS","Redis","Kubernetes"],"experience_years":6,"linkedin_summary":"6 yrs building high-throughput APIs at Stripe. Expert in Django, FastAPI, PostgreSQL and AWS. Startup culture advocate.","github_repos":48,"open_to_opportunities":True,"response_speed":"fast","personality":"eager"},
  {"id":"CAND002","name":"Ravi Kumar","title":"Senior Software Engineer","current_company":"Flipkart","location":"Remote","skills":["Python","FastAPI","Django","PostgreSQL","Docker","AWS","Redis"],"experience_years":7,"linkedin_summary":"Backend engineer at Flipkart. 7 yrs with Python, FastAPI, PostgreSQL and Docker on AWS. Love high-scale distributed systems.","github_repos":55,"open_to_opportunities":True,"response_speed":"medium","personality":"cautious"},
  {"id":"CAND003","name":"Elena Kozlov","title":"Senior Python Engineer","current_company":"JetBrains","location":"Remote","skills":["Python","Django","PostgreSQL","Docker","AWS","Redis","React"],"experience_years":5,"linkedin_summary":"Senior Python/Django engineer at JetBrains. 5 yrs building developer tools. Full-stack leaning, passionate about clean architecture.","github_repos":39,"open_to_opportunities":True,"response_speed":"fast","personality":"eager"},
  {"id":"CAND004","name":"James O'Brien","title":"Senior Backend Engineer","current_company":"Shopify","location":"Remote","skills":["Python","FastAPI","PostgreSQL","Docker","AWS","Redis","Kubernetes","GraphQL"],"experience_years":8,"linkedin_summary":"Backend architect at Shopify handling millions of events daily. Deep Python, FastAPI and Kubernetes expertise.","github_repos":62,"open_to_opportunities":True,"response_speed":"medium","personality":"cautious"},
  {"id":"CAND005","name":"Aisha Patel","title":"Senior Software Engineer","current_company":"Twilio","location":"Remote","skills":["Python","Django","FastAPI","PostgreSQL","Docker","AWS","Redis"],"experience_years":6,"linkedin_summary":"Python backend engineer at Twilio. 6 yrs with Django, FastAPI, AWS. Advocate for good documentation and developer experience.","github_repos":43,"open_to_opportunities":True,"response_speed":"fast","personality":"eager"},
  {"id":"CAND006","name":"Chen Wei","title":"Senior Platform Engineer","current_company":"ByteDance","location":"Remote","skills":["Python","Django","PostgreSQL","Docker","AWS","Redis","Celery"],"experience_years":9,"linkedin_summary":"Platform engineer at ByteDance. Expert in Python async systems, Celery workers and high-throughput pipelines. Prefers async-first teams.","github_repos":71,"open_to_opportunities":True,"response_speed":"slow","personality":"cautious"},
  {"id":"CAND007","name":"Maria Santos","title":"Senior Backend Engineer","current_company":"Nubank","location":"Remote","skills":["Python","FastAPI","PostgreSQL","Docker","AWS","Redis"],"experience_years":5,"linkedin_summary":"Backend engineer at Nubank. 5 yrs with FastAPI, PostgreSQL and AWS. Passionate about REST API design and cloud-native architectures.","github_repos":37,"open_to_opportunities":True,"response_speed":"medium","personality":"eager"},
  {"id":"CAND008","name":"Kwame Asante","title":"Senior Software Engineer","current_company":"Andela","location":"Remote","skills":["Python","Django","PostgreSQL","Docker","AWS","Redis","Elasticsearch"],"experience_years":7,"linkedin_summary":"Senior engineer at Andela building search and recommendation systems. Strong in Django REST framework and Elasticsearch.","github_repos":44,"open_to_opportunities":True,"response_speed":"medium","personality":"cautious"},
  {"id":"CAND009","name":"Dimitri Volkov","title":"Senior Python Engineer","current_company":"Yandex","location":"Remote","skills":["Python","FastAPI","PostgreSQL","Docker","AWS","Redis","Kubernetes"],"experience_years":6,"linkedin_summary":"Backend engineer at Yandex working on developer infrastructure. Strong Python and Kubernetes background. Open to remote roles.","github_repos":29,"open_to_opportunities":True,"response_speed":"slow","personality":"passive"},
  {"id":"CAND010","name":"Priya Sharma","title":"Senior Backend Developer","current_company":"Freshworks","location":"Remote","skills":["Python","Django","FastAPI","PostgreSQL","Docker","AWS","Redis"],"experience_years":5,"linkedin_summary":"Backend developer at Freshworks. 5 yrs with Django, FastAPI and PostgreSQL on AWS. Interested in product-focused startup roles.","github_repos":33,"open_to_opportunities":True,"response_speed":"fast","personality":"eager"},

  # ── GOOD MATCHES (20): Senior, missing 1-2 required skills ──
  {"id":"CAND011","name":"Arjun Mehta","title":"Senior Python Developer","current_company":"Razorpay","location":"Remote","skills":["Python","FastAPI","PostgreSQL","Docker","AWS","GraphQL"],"experience_years":5,"linkedin_summary":"Backend engineer at Razorpay. Strong FastAPI and AWS. Redis not yet in production stack but familiar with caching concepts.","github_repos":31,"open_to_opportunities":True,"response_speed":"medium","personality":"cautious"},
  {"id":"CAND012","name":"Sofia Andersen","title":"Senior Python Developer","current_company":"Zendesk","location":"Remote","skills":["Python","Django","PostgreSQL","AWS","Redis","Kubernetes"],"experience_years":6,"linkedin_summary":"Backend developer at Zendesk. Strong Django and AWS. Docker containerisation done via CI pipelines — not a hands-on Docker expert.","github_repos":28,"open_to_opportunities":True,"response_speed":"medium","personality":"cautious"},
  {"id":"CAND013","name":"David Kim","title":"Senior Backend Engineer","current_company":"Kakao","location":"Remote","skills":["Python","FastAPI","MySQL","Docker","AWS","Redis"],"experience_years":5,"linkedin_summary":"Backend engineer at Kakao. FastAPI and Docker expert. Primarily MySQL — have used PostgreSQL on side projects, comfortable switching.","github_repos":41,"open_to_opportunities":True,"response_speed":"medium","personality":"cautious"},
  {"id":"CAND014","name":"Leila Hassan","title":"Senior Software Engineer","current_company":"Careem","location":"Remote","skills":["Python","Django","PostgreSQL","Docker","GCP","Redis"],"experience_years":6,"linkedin_summary":"Cloud-native backend engineer at Careem. Deep GCP expertise. Strong Django and PostgreSQL. Open to AWS-first companies.","github_repos":36,"open_to_opportunities":True,"response_speed":"fast","personality":"eager"},
  {"id":"CAND015","name":"Marcus Thompson","title":"Staff Backend Engineer","current_company":"Coinbase","location":"Remote","skills":["Python","Django","FastAPI","PostgreSQL","Docker","AWS","Redis","Kubernetes","React"],"experience_years":10,"linkedin_summary":"Staff engineer at Coinbase leading platform architecture. 10 yrs building high-traffic systems. Looking for a technical leadership challenge.","github_repos":88,"open_to_opportunities":True,"response_speed":"slow","personality":"cautious"},
  {"id":"CAND016","name":"Yuki Tanaka","title":"Senior Python Developer","current_company":"Mercari","location":"Remote","skills":["Python","Flask","PostgreSQL","Docker","AWS","Redis"],"experience_years":5,"linkedin_summary":"Backend developer at Mercari. Flask and PostgreSQL power user. Interested in migrating to FastAPI or Django REST for next role.","github_repos":22,"open_to_opportunities":True,"response_speed":"medium","personality":"cautious"},
  {"id":"CAND017","name":"Fatima Al-Rashid","title":"Senior Backend Engineer","current_company":"Noon","location":"Remote","skills":["Python","Django","PostgreSQL","AWS","Redis","Celery"],"experience_years":6,"linkedin_summary":"Backend engineer with deep Django and PostgreSQL expertise. Docker is on active upskilling list. Fast-paced startup culture appeals to me.","github_repos":27,"open_to_opportunities":True,"response_speed":"fast","personality":"eager"},
  {"id":"CAND018","name":"Carlos Mendez","title":"Staff Python Engineer","current_company":"Rappi","location":"Remote","skills":["Python","FastAPI","PostgreSQL","Docker","AWS","Redis","GraphQL"],"experience_years":11,"linkedin_summary":"Staff engineer at Rappi. Broad backend experience. Not actively looking — prefer to be reached for exceptional opportunities only.","github_repos":59,"open_to_opportunities":True,"response_speed":"medium","personality":"passive"},
  {"id":"CAND019","name":"Nadia Okonkwo","title":"Senior Backend Developer","current_company":"Flutterwave","location":"Lagos, Nigeria (Hybrid)","skills":["Python","Django","PostgreSQL","AWS","Redis"],"experience_years":5,"linkedin_summary":"Backend developer at Flutterwave building payments infrastructure. Strong Django skills. Would consider remote-first roles.","github_repos":24,"open_to_opportunities":True,"response_speed":"medium","personality":"cautious"},
  {"id":"CAND020","name":"Liam O'Connor","title":"Senior Python Engineer","current_company":"Intercom","location":"Remote","skills":["Python","FastAPI","PostgreSQL","Docker","Redis","React"],"experience_years":6,"linkedin_summary":"Full-stack leaning engineer at Intercom. FastAPI expert. AWS is a gap — GCP-certified instead. Open to new challenges.","github_repos":46,"open_to_opportunities":True,"response_speed":"fast","personality":"eager"},
  {"id":"CAND021","name":"Tariq Al-Farsi","title":"Senior Backend Engineer","current_company":"Souq","location":"Remote","skills":["Python","FastAPI","MongoDB","Docker","AWS","Redis"],"experience_years":5,"linkedin_summary":"Backend engineer at Souq. Strong FastAPI and NoSQL. PostgreSQL is not primary but have worked with relational DBs. Currently passive.","github_repos":18,"open_to_opportunities":True,"response_speed":"slow","personality":"passive"},
  {"id":"CAND022","name":"Anna Petersen","title":"Staff Software Engineer","current_company":"Klarna","location":"Remote","skills":["Python","Django","FastAPI","PostgreSQL","Docker","AWS","Redis"],"experience_years":12,"linkedin_summary":"Staff engineer at Klarna. Led backend platform migrations. 12 yrs of Python. Looking for founding engineer or VP Eng roles.","github_repos":77,"open_to_opportunities":True,"response_speed":"medium","personality":"cautious"},
  {"id":"CAND023","name":"Rohit Verma","title":"Senior Python Developer","current_company":"Paytm","location":"Remote","skills":["Python","Django","PostgreSQL","Docker","AWS","Celery"],"experience_years":5,"linkedin_summary":"Backend engineer at Paytm building payment APIs. Strong Django and Celery. Redis is on learning roadmap this quarter.","github_repos":34,"open_to_opportunities":True,"response_speed":"medium","personality":"cautious"},
  {"id":"CAND024","name":"Isabelle Moreau","title":"Senior Backend Engineer","current_company":"Doctolib","location":"Remote","skills":["Python","FastAPI","PostgreSQL","Docker","Redis","Vue"],"experience_years":6,"linkedin_summary":"Backend engineer at Doctolib on health infrastructure. FastAPI and PostgreSQL are core stack. AWS gap — primarily GCP deployed.","github_repos":38,"open_to_opportunities":True,"response_speed":"medium","personality":"eager"},
  {"id":"CAND025","name":"Daniel Osei","title":"Senior Software Engineer","current_company":"mPharma","location":"Remote","skills":["Python","Django","PostgreSQL","Docker","AWS","Celery"],"experience_years":5,"linkedin_summary":"Backend engineer at mPharma building healthcare logistics APIs. Strong Django and task queue experience. Redis caching not yet in stack.","github_repos":21,"open_to_opportunities":True,"response_speed":"medium","personality":"cautious"},
  {"id":"CAND026","name":"Mei Lin","title":"Senior Python Engineer","current_company":"Alibaba","location":"Remote","skills":["Python","Django","PostgreSQL","Docker","Redis","Kubernetes"],"experience_years":5,"linkedin_summary":"Backend engineer at Alibaba. Expert in high-throughput Django APIs and Kubernetes. Limited AWS exposure — primarily private cloud.","github_repos":53,"open_to_opportunities":True,"response_speed":"fast","personality":"eager"},
  {"id":"CAND027","name":"Andrei Popescu","title":"Senior Backend Developer","current_company":"UiPath","location":"Remote","skills":["Python","FastAPI","PostgreSQL","AWS","Redis","GraphQL"],"experience_years":6,"linkedin_summary":"Backend developer at UiPath. FastAPI and PostgreSQL expert. Docker handled via CI pipelines rather than hands-on locally.","github_repos":30,"open_to_opportunities":True,"response_speed":"medium","personality":"cautious"},
  {"id":"CAND028","name":"Zara Ahmed","title":"Senior Python Developer","current_company":"Careem","location":"Remote","skills":["Python","Django","PostgreSQL","Docker","AWS"],"experience_years":5,"linkedin_summary":"Backend engineer at Careem. Solid Django and AWS. Redis caching not yet set up from scratch in production. Open to opportunities.","github_repos":19,"open_to_opportunities":True,"response_speed":"slow","personality":"passive"},
  {"id":"CAND029","name":"Patrick O'Sullivan","title":"Staff Python Engineer","current_company":"HubSpot","location":"Remote","skills":["Python","FastAPI","PostgreSQL","Docker","AWS","Redis","Kubernetes","React"],"experience_years":13,"linkedin_summary":"Staff engineer at HubSpot leading API platform. Very selective — only considering principal or CTO tracks at Series B+ startups.","github_repos":95,"open_to_opportunities":True,"response_speed":"slow","personality":"cautious"},
  {"id":"CAND030","name":"Kenji Watanabe","title":"Senior Backend Engineer","current_company":"Recruit Technologies","location":"Remote","skills":["Python","Django","MySQL","Docker","AWS","Redis"],"experience_years":5,"linkedin_summary":"Backend engineer at Recruit Technologies. Django and MySQL main stack. Redis and Docker daily. PostgreSQL is a gap — learning actively.","github_repos":26,"open_to_opportunities":True,"response_speed":"medium","personality":"cautious"},

  # ── PARTIAL MATCHES (15): right level wrong stack, OR right skills wrong level ──
  {"id":"CAND031","name":"Priya Nair","title":"Mid-level Backend Developer","current_company":"LogiSoft","location":"Bangalore (Hybrid)","skills":["Python","Django","MySQL","Docker"],"experience_years":3,"linkedin_summary":"Backend developer at LogiSoft working on supply chain tools. Django and Docker daily. Learning AWS and Kubernetes on the side.","github_repos":19,"open_to_opportunities":True,"response_speed":"fast","personality":"eager"},
  {"id":"CAND032","name":"Kofi Mensah","title":"Junior Backend Developer","current_company":"Andela","location":"Remote","skills":["Python","FastAPI","PostgreSQL","Git"],"experience_years":2,"linkedin_summary":"Junior developer at Andela. Comfortable with Python and FastAPI. Actively learning Docker and AWS. Excited for the next challenge.","github_repos":15,"open_to_opportunities":True,"response_speed":"fast","personality":"eager"},
  {"id":"CAND033","name":"Ana Lucia Reyes","title":"Backend Developer","current_company":"Despegar","location":"Remote","skills":["Python","Django","PostgreSQL"],"experience_years":2,"linkedin_summary":"Python backend developer at Despegar. Strong fundamentals in Django and relational databases. Still building cloud and DevOps experience.","github_repos":11,"open_to_opportunities":True,"response_speed":"medium","personality":"cautious"},
  {"id":"CAND034","name":"Thomas Eriksson","title":"Python Developer","current_company":"Klarna","location":"Remote","skills":["Python","FastAPI","MySQL","Docker"],"experience_years":2,"linkedin_summary":"Python developer at Klarna on internal tooling. Solid FastAPI and Docker skills. Primarily MySQL — planning to switch to PostgreSQL.","github_repos":14,"open_to_opportunities":True,"response_speed":"medium","personality":"cautious"},
  {"id":"CAND035","name":"Aditi Bansal","title":"Junior Python Developer","current_company":"Infosys","location":"Pune (Onsite)","skills":["Python","Django","SQLite"],"experience_years":1,"linkedin_summary":"Junior developer at Infosys. Python and Django primary tools. Looking for remote-first opportunities to grow quickly.","github_repos":8,"open_to_opportunities":True,"response_speed":"fast","personality":"eager"},
  {"id":"CAND036","name":"Samuel Gitau","title":"Junior Backend Engineer","current_company":"Safaricom","location":"Remote","skills":["Python","Flask","Git","PostgreSQL"],"experience_years":2,"linkedin_summary":"Junior engineer at Safaricom building internal tools. Python and PostgreSQL comfortable. Actively learning Docker and AWS fundamentals.","github_repos":10,"open_to_opportunities":True,"response_speed":"medium","personality":"cautious"},
  {"id":"CAND037","name":"Nina Johansson","title":"Python Developer","current_company":"Voi Technology","location":"Remote","skills":["Python","Django","Redis"],"experience_years":2,"linkedin_summary":"Backend developer at Voi. Django primary framework. Have used Redis for caching. Not yet comfortable with Docker or cloud services.","github_repos":9,"open_to_opportunities":True,"response_speed":"slow","personality":"passive"},
  {"id":"CAND038","name":"Raj Malhotra","title":"Junior Python Engineer","current_company":"Wipro","location":"Remote","skills":["Python","FastAPI","SQLite","Docker"],"experience_years":1,"linkedin_summary":"Junior engineer at Wipro. Built FastAPI projects and containerised with Docker. Looking for a startup environment to accelerate learning.","github_repos":13,"open_to_opportunities":True,"response_speed":"fast","personality":"eager"},
  {"id":"CAND039","name":"Emma Wilson","title":"Python Backend Developer","current_company":"Auto Trader UK","location":"Manchester (Hybrid)","skills":["Python","PostgreSQL","AWS"],"experience_years":2,"linkedin_summary":"Backend developer at Auto Trader. Strong PostgreSQL and AWS. Have not used Django or FastAPI in production — primarily data pipelines.","github_repos":16,"open_to_opportunities":True,"response_speed":"medium","personality":"cautious"},
  {"id":"CAND040","name":"Li Wei","title":"Junior Python Developer","current_company":"Tencent","location":"Remote","skills":["Python","Flask","MySQL","Git"],"experience_years":2,"linkedin_summary":"Junior developer with internship experience at Tencent. Flask and MySQL core stack. Eager to work on production-grade backend systems.","github_repos":18,"open_to_opportunities":True,"response_speed":"medium","personality":"cautious"},
  {"id":"CAND041","name":"Grace Oduya","title":"Python Backend Developer","current_company":"Paystack","location":"Remote","skills":["Python","Django","PostgreSQL","React"],"experience_years":2,"linkedin_summary":"Backend developer at Paystack. Django and PostgreSQL home base. Added React for internal dashboards. No Docker or cloud yet.","github_repos":17,"open_to_opportunities":True,"response_speed":"fast","personality":"eager"},
  {"id":"CAND042","name":"Viktor Petrov","title":"Python Developer","current_company":"Wrike","location":"Remote","skills":["Python","FastAPI","Docker","MongoDB"],"experience_years":2,"linkedin_summary":"Python developer at Wrike working on integrations. FastAPI and Docker experience. MongoDB — no PostgreSQL production experience yet.","github_repos":14,"open_to_opportunities":True,"response_speed":"medium","personality":"cautious"},
  {"id":"CAND043","name":"Camille Dubois","title":"Junior Python Developer","current_company":"Alan Health","location":"Paris (Onsite)","skills":["Python","Flask","PostgreSQL"],"experience_years":1,"linkedin_summary":"Junior developer at Alan Health. Flask and PostgreSQL basics. Looking for a remote role to grow into a full backend stack engineer.","github_repos":6,"open_to_opportunities":True,"response_speed":"slow","personality":"passive"},
  {"id":"CAND044","name":"Hiroshi Nakamura","title":"Python Developer","current_company":"Recruit","location":"Remote","skills":["Python","Django","MySQL","Redis"],"experience_years":2,"linkedin_summary":"Python developer at Recruit. Django and MySQL daily stack. Have used Redis for caching. Missing cloud and container experience.","github_repos":12,"open_to_opportunities":True,"response_speed":"medium","personality":"cautious"},
  {"id":"CAND045","name":"Rina Yamamoto","title":"Python Backend Developer","current_company":"CyberAgent","location":"Remote","skills":["Python","Django","PostgreSQL","Docker","AWS","Redis"],"experience_years":4,"linkedin_summary":"Backend developer at CyberAgent. Full Python stack. 4 years in, punching above weight. Actively seeking senior-level challenge.","github_repos":25,"open_to_opportunities":True,"response_speed":"fast","personality":"eager"},

  # ── POOR MATCHES (5): wrong stack or unrelated role ──
  {"id":"CAND046","name":"Tobias Richter","title":"Senior Java Architect","current_company":"SAP","location":"Berlin (Onsite)","skills":["Java","Spring Boot","Oracle DB","Jenkins","Azure","Hibernate"],"experience_years":12,"linkedin_summary":"Senior Java/Spring architect at SAP. Deep expertise in enterprise integrations and SOA. Not planning to switch stacks.","github_repos":7,"open_to_opportunities":False,"response_speed":"slow","personality":"passive"},
  {"id":"CAND047","name":"Alex Johnson","title":"Senior Frontend Engineer","current_company":"Figma","location":"Remote","skills":["JavaScript","React","Node.js","MongoDB","TypeScript","GraphQL"],"experience_years":6,"linkedin_summary":"Frontend engineer at Figma specialising in React and TypeScript. Strong Node.js for BFF layer. Not planning a stack switch.","github_repos":52,"open_to_opportunities":False,"response_speed":"medium","personality":"cautious"},
  {"id":"CAND048","name":"Svetlana Morozova","title":"Senior PHP Developer","current_company":"Badoo","location":"Moscow (Onsite)","skills":["PHP","Laravel","MySQL","Redis","Nginx"],"experience_years":7,"linkedin_summary":"Senior PHP/Laravel developer at Badoo. Eight years in PHP — not looking to switch languages. Strong database and caching background.","github_repos":9,"open_to_opportunities":False,"response_speed":"slow","personality":"passive"},
  {"id":"CAND049","name":"Deepak Joshi","title":"Senior Data Scientist","current_company":"Mu Sigma","location":"Remote","skills":["Python","TensorFlow","Keras","R","Pandas","NumPy","Scikit-learn"],"experience_years":5,"linkedin_summary":"Data scientist at Mu Sigma. Python for ML and analytics, not web backends. No Django, FastAPI, Docker or cloud infrastructure experience.","github_repos":23,"open_to_opportunities":False,"response_speed":"medium","personality":"passive"},
  {"id":"CAND050","name":"Bashir Rahimi","title":"Senior Ruby Engineer","current_company":"Shopify (Ruby team)","location":"Remote","skills":["Ruby","Rails","PostgreSQL","Docker","Redis","Sidekiq"],"experience_years":6,"linkedin_summary":"Rails engineer at Shopify. Deep PostgreSQL and Redis expertise via Ruby. Not planning to move to Python — Rails ecosystem is home.","github_repos":34,"open_to_opportunities":False,"response_speed":"slow","personality":"passive"},
]

Path("data/candidates.json").write_text(
    json.dumps(candidates, indent=2, ensure_ascii=False),
    encoding="utf-8"
)
print(f"✅ Written {len(candidates)} candidates to data/candidates.json")
